name: podium
description: A New Standard of Living.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0"
  flutter: 3.3.6

dependencies:
  authentication_repo:
    path: lib/packages/authentication_repo
  bloc: ^8.1.2

  build_runner: ^2.4.4
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.7.1
  cloud_functions: ^4.3.3
  cloud_functions_web: ^4.5.1
  dots_indicator: ^3.0.0
  dropdown_button2: ^2.1.4
  envied: ^0.3.0+3
  envied_generator: ^0.3.0+3
  equatable: ^2.0.3
  file_picker: ^5.3.2
  firebase_analytics: ^10.4.1
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  firebase_storage: ^11.2.1
  fl_chart: ^0.63.0
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_email_sender: ^6.0.0
  flutter_facebook_auth: ^5.0.8
  flutter_launcher_icons: ^0.13.1
  flutter_pdfview: ^1.3.0
  flutter_platform_widgets: ^3.3.5
  flutter_stripe: ^9.2.2
  flutter_stripe_web: ^4.1.0
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.4.0
  form_builder_image_picker: ^4.0.0
  form_inputs:
    path: lib/packages/form_inputs
  formz: ^0.6.0
  go_router: ^9.0.0
  google_fonts: ^4.0.4
  http: ^0.13.0
  image_picker: ^0.8.9
  image_picker_web: ^3.0.0+1
  intl: ^0.18.1
  meta: ^1.8.0
  mockito: ^5.4.2
  path_provider: ^2.0.11
  permission_handler: ^10.3.0
  progressive_image: ^2.0.1
  provider: ^6.0.5
  sign_in_button: ^3.2.0
  sign_in_with_apple: ^5.0.0
  stripe_checkout: ^1.0.0
  syncfusion_flutter_charts: ^22.1.34
  url_launcher: ^6.1.11
  url_strategy: ^0.2.0

dev_dependencies:
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/src/assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: lib/src/assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: lib/src/assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: lib/src/assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: lib/src/assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: lib/src/assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: lib/src/assets/fonts/Roboto-Black.ttf
          weight: 900

flutter_icons:
  android: true
  ios: true
  image_path: lib/src/assets/images/podium_logo_square.png
